---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: yml
- type: document
  path: _data/members.yml
  label: Members
- type: document
  path: _data/*
  label: Data
- type: directory
  path: _publications
  label: Publications
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: pages
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: images
public_path: "/files"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: jekyll serve
