---
label: Project
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: name
- name: publications
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: publications
- name: members
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: members
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
- name: thumbnail
  type: text
  config:
    required: false
  label: thumbnail
- name: about
  type: text
  config:
    required: false
  label: about
pages:
- _projects/rdtscan.md
- _projects/rdtscan.md
